# Generated by Django 3.0.4 on 2020-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200407_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorting',
            name='remove_same',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
