# Generated by Django 3.0.4 on 2020-04-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sorting_remove_same'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorting',
            name='remove_same',
        ),
    ]
