# Generated by Django 3.0.4 on 2020-04-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200409_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorting',
            name='algorithm',
            field=models.CharField(choices=[('Bubble', 'Bubble'), ('Insertion', 'Insertion'), ('Merge', 'Merge'), ('Shell', 'Shell')], default='Buble', max_length=9),
        ),
    ]
