# Generated by Django 3.0.4 on 2020-04-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200414_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorting',
            name='algorithm',
            field=models.CharField(choices=[('Bubble', 'Bubble'), ('Insertion', 'Insertion'), ('Merge', 'Merge'), ('Shell', 'Shell'), ('Selection', 'Selection')], default='Buble', max_length=9),
        ),
    ]
