# Generated by Django 5.0.4 on 2024-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sorting",
            fields=[
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("Bubble", "Bubble"),
                            ("Insertion", "Insertion"),
                            ("Merge", "Merge"),
                            ("Shell", "Shell"),
                        ],
                        default="Buble",
                        max_length=9,
                    ),
                ),
                ("numbers", models.TextField()),
                ("file", models.FileField(upload_to="")),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
