# Generated by Django 4.2.11 on 2024-04-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sorting",
        ),
    ]
