# Generated by Django 4.2.11 on 2024-04-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0002_delete_sorting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sorting",
            fields=[
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("Bubble", "Bubble"),
                            ("Insertion", "Insertion"),
                            ("Merge", "Merge"),
                            ("Shell", "Shell"),
                        ],
                        default="Buble",
                        max_length=9,
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
